name: Release Tag

permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  ensure_rust_cargo_toml_version:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: sintax_rs

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Ensure rust cargo toml version
        run: |
          TOML_PACKAGE_VERSION=$(grep "^version = " Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
          LOCK_PACKAGE_VERSION=$(grep -A 1 "name = \"${{ env.PACKAGE_NAME }}\"" Cargo.lock | grep "^version = " | head -1 | sed 's/version = "\(.*\)"/\1/')

          CURRENT_TAG=${{ github.ref_name }}

          echo "Repository version ${CURRENT_TAG}"
          echo "Cargo.toml version ${TOML_PACKAGE_VERSION}"
          echo "Cargo.lock version ${LOCK_PACKAGE_VERSION}"

          if [[ "$CURRENT_TAG" != "v$TOML_PACKAGE_VERSION" ]]; then
            echo "Error: Cargo.toml ${TOML_PACKAGE_VERSION} version does not match tag version ${CURRENT_TAG}"
            exit 1
          fi

          if [[ "$CURRENT_TAG" != "v$LOCK_PACKAGE_VERSION" ]]; then
            echo "Error: Cargo.lock ${LOCK_PACKAGE_VERSION} version does not match tag version ${CURRENT_TAG}"
            exit 1
          fi

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --all-features

  create_release:
    needs: [ensure_rust_cargo_toml_version, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload_binaries:
    needs: [ensure_rust_cargo_toml_version, test, create_release]

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Upload binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bin: sintax_rs
          target: ${{ matrix.target }}
          checksum: sha256
          archive: $bin-$tag-$target
          manifest_path: Cargo.toml

  # publish_to_crates_io:
  #   needs: [upload_binaries]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v6

  #     - name: Install Rust toolchain
  #       uses: dtolnay/rust-toolchain@stable

  #     - name: "Dry run check"
  #       run: cargo publish --dry-run --all-features

  #     - name: Authenticate with crates.io
  #       uses: rust-lang/crates-io-auth-action@v1
  #       id: crates-io-auth

  #     - name: Publish to crates.io
  #       run: cargo publish
  #       env:
  #         CARGO_REGISTRY_TOKEN: ${{ steps.crates-io-auth.outputs.token }}
